pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "project.views"
    tracer:
        client: "jaeger"
        host: "localhost"
        component_name: "test download"
    metrics: true
    

  config:
    DEBUG: false
    TESTING: false
    APP_NAME: test download
    APPLICATION_ROOT : /test_download
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    DATABASE: db.sqlite3
    SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3